### ISSUE TITLE
Return type problem

### ISSUE THREAD

**Issue by uiuytb** [altmp/altv-types#313]
Hello, 

I don't know if I misunderstood how rpc types works but should not the return type of the onRpc be `Promise<ReturnType<shared.ICustomServerClientRpc[K]>> | ReturnType<shared.ICustomServerClientRpc[K]>)` and not `Promise<ReturnType<shared.ICustomClientServerRpc[K]>> | ReturnType<shared.ICustomClientServerRpc[K]>)` in the client module ?

It's at line 2612: https://github.com/altmp/altv-types/blob/885493e2ea0612b492815f1124dfa57ba1cb37d2/client/index.d.ts#L2612

**Comment by xxshady** [comment]
sorry for ignoring, gonna fix that
